[example]
description = "Example plugin"
author = "YOU"
## NOTE: version is omitted here because I don't like having multiple places
## to update the version string. Feel free to add it back in.
#
# version = "v0.0.0"

[example.build]
output = "build/src/example.so"
steps = [
    "meson setup build",
    "meson compile -Cbuild"
]
